#!/bin/sh

VERSION=`git symbolic-ref HEAD 2> /dev/null | cut -b 12-`-`git log --pretty=format:%h -1 || git describe --tags --exact-match`
git checkout pom.xml
sed -i '' "s/__VERSION__/$VERSION/g" pom.xml
mvn package
git checkout pom.xml
